let CONSTANTS = {};

CONSTANTS.MESSAGES = require('./messages');

CONSTANTS.AVAILABLE_AUTHS = {
    USER: "user"
};

CONSTANTS.DEFAULT_PROFILE_IMAGE = 'profile.jpg';

CONSTANTS.SECURITY = {
    JWT_SIGN_KEY: "RANDOM_JWT_KEY_TO_PASTE_HERE",
    BCRYPT_SALT: 2564414
};

CONSTANTS.ERROR_TYPES = {
    DATA_NOT_FOUND: "DATA_NOT_FOUND",
    BAD_REQUEST: "BAD_REQUEST",
    MONGO_EXCEPTION: "MONGO_EXCEPTION",
    ALREADY_EXISTS: "ALREADY_EXISTS",
    FORBIDDEN: "FORBIDDEN",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    UNAUTHORIZED: "UNAUTHORIZED"
};

CONSTANTS.GENDER = {
    MALE: 'male',
    FEMALE: 'female',
    OTHER: 'other'
};

CONSTANTS.NORMAL_PROJECTION = { createdAt: 0, updatedAt: 0, __v: 0 };

CONSTANTS.TECHNOLOGY = {
    NODE_JS: 'Nodejs',
    REACT: 'React',
    SQL: 'SQL'
}

module.exports = CONSTANTS;
